### ISSUE TITLE
Missing snapshot summary

### ISSUE THREAD

**Issue by SimenB** [rickhanlonii/jest-silent-reporter#15]
Made debugging https://github.com/facebook/jest/pull/8665 confusing as we only saw the exit status but no errors. Temporarily using the default reporter had this output:
![image](https://user-images.githubusercontent.com/1404810/61941621-23155080-af98-11e9-8061-bd818b088304.png)

**Comment by SimenB** [comment]
Solved by #23 I believe?

**Comment by NickHeiner** [comment]
This seems be causing a lot of problems for people with https://github.com/facebook/jest/issues/9324. It might be good to make `showPaths` default to `true`.

**Comment by NickHeiner** [comment]
Also, I don't think #23 universally solves it. I observed an issue where Jest exited with status code `1` because a snapshot was obsolete, but it wasn't related to the file I was running the test for:

```
 PASS   lint  packages/darwin/src/components/AcessibilityText/index.js
  ✓ ESLint (843 ms)

Snapshot Summary
 › 5 snapshot files obsolete from 5 test suites. To remove them all, re-run jest with `-u`.
   ↳   • servers/tvui-nodequark/src/routes/videos/stubsFocusedTall/__functional__/__snapshots__/route.js.snap
```

Therefore, when I did `console.log(testResult);` in `onTestResult`, I didn't see anything about this snapshot, which is not surprising, because it's for a different file. 

I'm not sure what Jest API should be used to figure out if unrelated snapshots are going to cause a non-0 status code exit.
