### ISSUE TITLE
Add 0.3 release to github

### ISSUE THREAD

**Issue by havenchyk** [rickhanlonii/jest-silent-reporter#22]
Hey all, I see that master is not a main branch here, so latest changes are not shown on the commit history. 

GitHub releases are also not created for v0.3

What I suggest is to

- change default branch back to master
- cherry pick commit from master to current default branch
- setup automatic GitHub releases
- add changelog
- setup semantic releases + conventional commits

What's your thoughts on it, can contributors help with it, would maintainers help/support such initiative?

**Comment by SimenB** [comment]
main branch should probably be `main`, except for that I think it all makes sense.

@rickhanlonii would you like to move this repo to http://github.com/jest-community?

**Comment by rickhanlonii** [comment]
Hey @havenchyk, thanks for submitting the issue!

I've deleted the `master` branch and will keep the current BLACK-LIVES-MATTER branch as the main branch until github standardizes on `main` with all of their tooling (which should be soon if I understand correctly). The BLACK-LIVES-MATTER branch is now up to date.

Automatic releases and a changelog make sense but don't seem necessary because since this package doesn't change very often (3 times in 3 years), the time it would take to set it up is more than the time it takes to just manually create the releases.

Similarly, as a small package with not many changes, I'm not going to adopt conventional commits, but I am using semantic versioning.

Going to close this for now, but if anything changes we can revisit the automation or branch names.

**Comment by rickhanlonii** [comment]
@SimenB I'd like to keep this on my personal account, but I've invited you as a collaborator 👍

**Comment by havenchyk** [comment]
Thanks!
